name: hag_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - librosa
  - aeon>=0.10
  - ffmpeg
  - tensorflow
  - optuna
  - jupyterlab
  - tqdm
  - dcor
  - pip
  - pip:
    - reservoirpy
    - torch
    - torchaudio
    - jupyterlab-execute-time
    - jupyterlab-optuna
    - cmaes